# vim:ft=ansible
- name: Create Config Directories
  file: 
    path: "{{item}}"
    state: directory
  with_items:
   - "{{ dotfiles.config.directories }}"

- name: Copy Configuration Files
  copy:
    src: "{{ item.src }}"
    dest: "~/{{ item.dest }}"
    mode: "0644"
    force: no
  with_items:
    - "{{ dotfiles.config.files }}"

- name: Link Dotfiles
  copy:
    src: "{{ repos.local_dir }}/dotfiles/{{ item.src }}"
    dest: "~/{{ item.dest }}"
    mode: "0644"
    force: no
  with_items:
    - "{{ dotfiles.sources }}"