# vim:ft=ansible
- name: Create Config Directories
  file: 
    path: "{{item}}"
    state: directory
  with_items:
   - "{{ dotfiles.config.directories }}"

- name: Link Dotfiles
  file:
    src: "{{ repos.local_dir }}/dotfiles/{{ item.src }}"
    dest: "~/{{ item.dest }}"
    mode: "0644"
    force: no
    state: link
  with_items:
    - "{{ dotfiles.sources }}"