
- name: Install Caskroom
  command: "{{ item }}"
  with_items:
    - brew install caskroom/cask/brew-cask
    - brew tap caskroom/versions

- name: Install Caskroom Apps
  homebrew_cask:
    name: "{{item}}"
    state: "present"
  with_items:
    - "{{ cask_apps }}"
  ignore_errors: yes
