# EMN DevOps initializer

- name: Provision Unix Environment
  hosts: remote
  gather_facts: true
  roles:
    - { role: cli, tags: [ 'init', 'cli' ]  }
    - { role: apps, tags: [ 'init', 'apps' ]  }
    # - { role: repos, tags: [ 'init', 'repos' ]  }
    # - { role: dotfiles, tags: [ 'init', 'dotfiles' ]  }
